"""The committed notebooks are exactly what their generators write (ruling 44).

Both notebooks are produced by ``scripts/make_verify_nb.py`` and ``scripts/make_summary_nb.py``.
Before this branch those generators lived on one machine and were in no branch at all, so the
notebook could not be regenerated by anyone else and the generator and the committed file would
have diverged silently at the next edit -- whichever ran last destroying the other's work.

Committing the generators only removes that hazard while something keeps the two in step. That
is this file: it fails the moment the committed notebook and its generator's output differ, so
a hand-edit of the notebook, or an edit to the generator that was never run, is caught here
rather than discovered by the next person who runs the generator.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO = Path(__file__).resolve().parents[1]
TASK_DIR = REPO / "docs" / "tasks" / "rung1-held-out-prediction"

#: Each generator and the notebook it is the source of.
GENERATORS: tuple[tuple[str, str], ...] = (
    ("make_verify_nb.py", "verify.ipynb"),
    ("make_summary_nb.py", "summary.ipynb"),
)

pytestmark = pytest.mark.step_document


def _load(script: str) -> ModuleType:
    """Import a generator by path; ``scripts`` is not a package."""
    path = REPO / "scripts" / script
    spec = importlib.util.spec_from_file_location(path.stem, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize(("script", "notebook"), GENERATORS)
def test_the_generator_reproduces_the_committed_notebook(script: str, notebook: str) -> None:
    """Byte for byte, not merely cell for cell.

    A comparison of parsed objects would pass a generator whose output differed in indentation,
    key order or escaping -- which is a whole-file diff on every save, and exactly the drift
    that makes a generated file stop being regenerated.
    """
    produced = _load(script).notebook_bytes()
    committed = (TASK_DIR / notebook).read_bytes()
    assert produced == committed, (
        f"{notebook} differs from what scripts/{script} writes ({len(committed):,} bytes "
        f"committed, {len(produced):,} generated). Run `uv run python scripts/{script}` and "
        "commit the result, or carry the notebook's edit back into the generator."
    )


@pytest.mark.parametrize(("script", "notebook"), GENERATORS)
def test_the_generated_notebook_carries_no_outputs(script: str, notebook: str) -> None:
    """PROCESS section 3: both notebooks are committed WITHOUT outputs, so the numbers and
    figures a reviewer sees are the ones their own execution produced. The generator is now the
    only thing that writes them, so the guarantee belongs to it."""
    document = json.loads(_load(script).notebook_bytes())
    code = [cell for cell in document["cells"] if cell["cell_type"] == "code"]
    assert code, f"{notebook} has no code cells"
    assert all(cell["outputs"] == [] for cell in code)
    assert all(cell["execution_count"] is None for cell in code)


@pytest.mark.parametrize(("script", "notebook"), GENERATORS)
def test_the_generator_writes_where_it_is_asked(script: str, notebook: str, tmp_path: Path) -> None:
    """``--out`` exists so this suite, and anyone comparing, can run the generator without
    touching the committed file."""
    module = _load(script)
    target = tmp_path / notebook
    module.main(["--out", str(target)])
    assert target.read_bytes() == (TASK_DIR / notebook).read_bytes()
